### ISSUE TITLE
Result formatting: Base, vectors of strings

### ISSUE THREAD

**Issue by tecosaur** [nico202/ob-julia#1]
Vectors of numbers are displayed nicely, but when I use strings suddenly an hline is inserted.
```org
#+begin_src julia
[1, 2, 3]
#+end_src

#+RESULTS:
| 1 |
| 2 |
| 3 |

#+begin_src julia
["a", "b", "c"]
#+end_src

#+RESULTS:
| a |
|---|
| b |
| c |
```

**Comment by nico202** [comment]
Yeah this is the results of an heuristic I was using to detect if the output should be a table or not, based on the first element of the result.  If the element is a string (and results type is 'auto) the result was considered as a table.

I just removed it in commit 85e3267b3cdcd3d5005df26c009d551eccc48cf4, but I'd keep this bug open so we can come back later and decide whether some heuristic is required.

**Comment by tecosaur** [comment]
I think we may need to rethink that heuristic. Perhaps it would be better for the Julia component to suggest the Org results format that should be used, and `:results auto` should pay attention to that instead of making guesses? I say this because I've got some more examples of problematic behaviour coming up :stuck_out_tongue:

**Comment by tecosaur** [comment]
The main case that occurs to me when we'd want an hline in the results is when showing a `DataFrame`. I'm about to manually add this on the Julia side, and so will close this issue until other cases come up.
