### ISSUE TITLE
Results formatting: LinearAlgebra, UniformScaling

### ISSUE THREAD

**Issue by tecosaur** [nico202/ob-julia#4]
This is a rather minor one, `LinearAlgebra` has a type `UniformScaling` that displays rather simply in the REPL.
```julia
julia> UniformScaling(2)
UniformScaling{Int64}
2*I
```

This could be a matter of preference, but while the current output is alright
```org
#+begin_src julia
UniformScaling(2)
#+end_src

#+RESULTS:
: UniformScaling{Int64}(2)
```

I think it would be nicer if `2*I` was output instead.

**Comment by nico202** [comment]
In 657daf8 I'm falling back to text/plain for all types we don't have a special formatting.  This would be:
```org
#+begin_src julia
import LinearAlgebra: UniformScaling
UniformScaling(2)
#+end_src

#+RESULTS:
| LinearAlgebra.UniformScaling{Int64} |
| 2*I                                 |
```

I won't remove the first line, but I'd prefer the output not to be a table, so I keep this open until I rework that part of the code

**Comment by tecosaur** [comment]
Sounds good to me :+1:
