### ISSUE TITLE
Formatting results: DataFrames

### ISSUE THREAD

**Issue by tecosaur** [nico202/ob-julia#7]
##### This concerns the `DataFrames` package

There are one major and one minor issue with the way data frames are formated at the moment, as I see it.

The major issue is the strange result of the table-ification that occurs by default

```org
#+begin_src julia
DataFrame(A = 1:4, B = ["M", "F", "F", "M"])
#+end_src

#+RESULTS:
| 4×2 DataFrame         |
|-----------------------|
| Row │ A      B        |
| │ Int64  String       |
| ─────┼─────────────── |
| 1 │     1  M          |
| 2 │     2  F          |
| 3 │     3  F          |
| 4 │     4  M          |
```

There's also the issue that if you try to view a large data frame, instead of being truncated as the REPL does:

```julia
julia> DataFrame(A = 1:200, B = repeat(["A"], 200))
200×2 DataFrame
 Row │ A      B
     │ Int64  String
─────┼───────────────
   1 │     1  A
   2 │     2  A
   3 │     3  A
   4 │     4  A
   5 │     5  A
   6 │     6  A
   7 │     7  A
   8 │     8  A
   9 │     9  A
  10 │    10  A
  11 │    11  A
  ⋮  │   ⋮      ⋮
 191 │   191  A
 192 │   192  A
 193 │   193  A
 194 │   194  A
 195 │   195  A
 196 │   196  A
 197 │   197  A
 198 │   198  A
 199 │   199  A
 200 │   200  A
     179 rows omitted
```

Every row is shown in Org, which probably isn't great.

**Comment by nico202** [comment]
I added back the DataFrames support from my previous implementation (7cc71a7).

```julia
#+begin_src julia :results table :async
  using DataFrames
  df = DataFrame(A = string.(1:4), B = 4.0:-1.0:1.0)
#+end_src

#+RESULTS:
| A |   B |
|---+-----|
| 1 | 4.0 |
| 2 | 3.0 |
| 3 | 2.0 |
| 4 | 1.0 |
```

However, as for sparse matrix, I prefer to have all output or the advantage of having `:var` is lost.  We can thing of a generic way to limit the output lines with an optional parameter (e.g., `#+begin_src julia :limit 200`) along with a defcustom variable if the output slows down the org buffer, but given that results can be hidden (`org-cycle` with the cursor over `#+results:`) I'd say that's low priority.
