### ISSUE TITLE
Formatting results: Latexify

### ISSUE THREAD

**Issue by tecosaur** [nico202/ob-julia#8]
##### This concerns the `Latexify` package

Latexify results that produce inline LaTeX are alright:

```org
#+begin_src julia
latexify(:(gamma(3)))
#+end_src

#+RESULTS:
: $\Gamma\left( 3 \right)$
```

But I think it would be great if the output could be:
```
#+RESULTS:
\(\Gamma\left( 3 \right)\)
```

For multi-line / environment results, like `latexify([1 2; 3 4])` an error is produced `Error (org-babel): Error reading results: (end-of-file)` and no output.

For reference, in the REPL I see

```julia
julia> using Latexify

julia> latexify([1 2; 3 4])

L"\begin{equation}
\left[
\begin{array}{cc}
1 & 2 \\
3 & 4 \\
\end{array}
\right]
\end{equation}
"
```

Once again, I think it would be neat if the LaTeX could be inserted directly.

# Stretch goals

## Auto-rendering

If `(bound-and-true-p org-fragtog-mode)` call `org-latex-preview` on the output

## Auto-conversion of other objects to LaTeX

It would be really nice have a `:latexify t` header which either (a) heuristically, or (b) via try-catch converts Julia objects to LaTeX and inserts that result.

Example desired result
```
#+begin_src julia
[1 2; 3 4]
#+end_src

#+RESULTS:
\begin{equation}
\left[
\begin{array}{cc}
1 & 2 \\
3 & 4 \\
\end{array}
\right]
\end{equation}

#+begin_src julia
using Symbolics
@variables t
2^sin(t) + cos(t)/t
#+end_src

#+RESULTS:
\begin{equation}
\frac{\cos\left( t \right)}{t} + 2^{\sin\left( t \right)}
\end{equation}
```

## Motivation

I think the combination of both of these could make for a *really* nice experience.

![image](https://user-images.githubusercontent.com/20903656/115968572-22de2680-a56b-11eb-81cf-48569d9b111e.png)

_NB: This would require `latex-environment` to be added to `org-babel-result-end`, but we can talk to the ML about that. Then we'd also need to make sure any `$ ... $` results are changed to a latex environment._

**Comment by tecosaur** [comment]
A patch to enable the second stretch goal has been submitted: https://lists.gnu.org/archive/html/emacs-orgmode/2021-04/msg00563.html

**Comment by tecosaur** [comment]
I think I have a fix for the bug here (at least for this package).
```
#+begin_src julia
using Latexify
using LaTeXStrings
function display(d::ObJuliaDisplay, ::MIME"text/org", l::LaTeXStrings.LaTeXString)
    print(d.io, l.s)
end
latexify([1 2; 3 4])
#+end_src

#+RESULTS:
| \begin{equation}  |
| \left[            |
| \begin{array}{cc} |
| 1 & 2 \\          |
| 3 & 4 \\          |
| \end{array}       |
| \right]           |
| \end{equation}    |
```

**Comment by nico202** [comment]
OT: how are you replacing begin_src with >>?

**Comment by tecosaur** [comment]
That's some `prettify-symbols-mode` config done by Doom.

**Comment by nico202** [comment]
Still need to figure out the results type heuristic, but for now here (acd4189 and 8297465) how it goes:
```julia
#+begin_src julia
  using Latexify
  # we have latxify, but nothing happens
  zeros(2, 3)
#+end_src

#+RESULTS:
| 0.0 | 0.0 | 0.0 |
| 0.0 | 0.0 | 0.0 |

#+begin_src julia :results latex
    using Latexify
# we have latexify and the output is latex, latexify it
    [1 2; 3 4]
#+end_src

#+RESULTS:
#+begin_export latex
| \begin{equation}  |
| \left[            |
| \begin{array}{cc} |
| 1 & 2 \\          |
| 3 & 4 \\          |
| \end{array}       |
| \right]           |
| \end{equation}    |
#+end_export

#+begin_src julia :results latex
# Output is latex but we don't have latexify, fallback to standard output.  This might be fixed with a custom export like the one in html
  zeros(2, 3)
#+end_src

#+RESULTS:
#+begin_export latex
[0.0 0.0 0.0; 0.0 0.0 0.0]
#+end_export

#+begin_src julia
 using Latexify
# the output is a latexify object, output latex
 latexify([1 2; 3 4])
#+end_src

#+RESULTS:
| \begin{equation}  |
| \left[            |
| \begin{array}{cc} |
| 1 & 2 \\          |
| 3 & 4 \\          |
| \end{array}       |
| \right]           |
| \end{equation}    |

```
#+begin_src julia :results latex
  zeros(2, 3)
#+end_src

#+RESULTS:
#+begin_export latex
[0.0 0.0 0.0; 0.0 0.0 0.0]
#+end_export

Btw, the error : `Error (org-babel): Error reading results: (end-of-file)` happens because of `org-babel-import-elisp-from-file`, hopefully will be fixed along with the better heuristic

**Comment by tecosaur** [comment]
With the heuristic, perhaps "if first line starts with `\begin{`, output raw" could work?

Aside from that, I think it would be nice to be able to plop a `#+properties: header-args:julia :results latex` (or `:latexify t` or similar) at the top of the file and see raw LaTeX output when possible, and then the "normal" output otherwise.
By "normal" I mean that if hypothetically Latexify didn't support 2D arrays, the result should be 
```
| 1 | 2 |
| 3 | 4 |
```
not
```
#+begin_export latex
[1 2; 3 4]
#+end_export
```

What do you think?

**Comment by tecosaur** [comment]
Update: my patch has just been merged :partying_face:

**Comment by tecosaur** [comment]
Using the merged functionality, I've almost managed to whip up a working prototype of the second stretch goal.

I'm currently stuck because the following doesn't work as I'd imagine:
https://github.com/nico202/ob-julia/blob/5eb63152bb182db4dc81802770a2368f42ffa049/ob-julia.el#L293

When this `'raw` case is true, I still get verbatim output.

**Comment by tecosaur** [comment]
I've managed to get this to work, but I've needed to advise `org-babel-insert-result`

```lisp
(defun ob-julia-latexify-make-raw (orig-fn result &optional result-params info hash lang)
  (unless (and (stringp result)
               (string= lang "julia")
               (let ((latex-env (string-match-p "^\\\\begin" result))
                     (latex-disp (string-match-p "^\\$\\$.*\\$\\$$" result))
                     (latex-inline (string-match-p "^\\$.*\\$$" result)))
                 (when (or latex-env latex-disp latex-inline)
                   (when (or latex-disp latex-inline)
                     (setf result (replace-regexp-in-string "^\\$\\$?\\(.*\\)\\$\\$?$"
                                                            "\\\\begin{equation*}\n\\1\n\\\\end{equation*}"
                                                            result)))
                   (funcall orig-fn result (append result-params '("raw")) info hash lang)
                   (when org-fragtog-mode
                     (save-excursion
                       (goto-char (org-babel-where-is-src-block-result nil info))
                       (forward-line 1)
                       (org-latex-preview)))
                   t)))
    (funcall orig-fn result result-params info hash lang)))

(advice-add 'org-babel-insert-result :around #'ob-julia-latexify-make-raw)
```

**Comment by tecosaur** [comment]
A little demo:

https://user-images.githubusercontent.com/20903656/116806851-59ff9980-ab62-11eb-92cb-d34129077c3f.mp4

**Comment by tecosaur** [comment]
Almost finished re-implementing this :slightly_smiling_face:

**Comment by tecosaur** [comment]
Done in dcd22c0.
